name: "Networking"

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"

############
# Targets
############

targets:
  Networking:
    type: framework
    platform: [iOS]
    sources:
      - Sources
  NetworkingTests:
    type: bundle.unit-test
    platform: [iOS]
    sources:
      - Tests
    dependencies:
      - target: Networking_${platform}