name: "R3Networking"

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"

############
# Targets
############

targets:
  R3Networking:
    type: framework
    platform: iOS
    sources:
      - Sources
    preBuildScripts:
      - name: "Lint"
        script: | 
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  R3NetworkingTests:
    type: bundle.unit-test
    platform: [iOS]
    sources:
      - Tests
    dependencies:
      - target: R3Networking